definitions:
  app.SOut:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  errenum.Resp:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
info:
  contact: {}
  description: Go 语言编程之旅:一起用Go写项目
  license: {}
  termsOfService: https://github.com/spider-nns/web-gin
  title: web-gin
  version: v1
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签
        in: body
        name: name
        schema:
          type: string
      - description: 状态
        in: body
        name: state
        schema:
          type: integer
      - description: 页，默认1
        in: body
        name: pageNo
        schema:
          type: integer
      - description: 页大小，默认10
        in: body
        name: pageSize
        schema:
          type: integer
      produces:
      - application/json
  /api/v1/tags/:
    post:
      parameters:
      - description: 标签id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.SOut'
        "500":
          description: 失败
          schema:
            $ref: '#/definitions/errenum.Resp'
  /api/v1/tags/{id}:
    get:
      parameters:
      - description: 标签id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.SOut'
        "500":
          description: 失败
          schema:
            $ref: '#/definitions/errenum.Resp'
    put:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.SOut'
        "500":
          description: 失败
          schema:
            $ref: '#/definitions/errenum.Resp'
swagger: "2.0"
